forum_ajax:
    path: /con4gis/forumService/{id}/{req}
    defaults:
        _scope: frontend
        _controller: "con4gisForumBundle:Forum:ajax"
    requirements:
        id: \d+
        req: .*

forum_history_ajax:
    path: /con4gis/forumService/{id}
    defaults:
        _scope: frontend
        _controller: "con4gisForumBundle:Forum:ajax"
    requirements:
        id: \d+

forum_pn:
    path: /con4gis/forumPnService/{actionFragment}
    defaults:
        _scope: frontend
        _controller: "con4gisForumBundle:Forum:personalMessage"
    requirements:
        actionFragment: .*

thread_sub:
    path: /con4gis/forum/threadsub/
    defaults:
        _scope: frontend
        _controller: "con4gisForumBundle:Subscription:changeThreadSubscription"
        methods: [POST]

forum_sub:
    path: /con4gis/forum/forumsub/
    defaults:
        _scope: frontend
        _controller: "con4gisForumBundle:Subscription:changeForumSubscription"
        methods: [POST]

controllers:
    resource: '../../Controller/'
    type:     annotation
