forum_ajax:
    path: /con4gis/forumService/{id}/{req}
    controller: con4gis\ForumBundle\Controller\ForumController::ajaxAction
    requirements:
        id: '\d+'
        req: '.*'

forum_history_ajax:
    path: /con4gis/forumService/{id}
    controller: con4gis\ForumBundle\Controller\ForumController::ajaxAction
    requirements:
        id: '\d+'

forum_pn:
    path: /con4gis/forumPnService/{language}/{action}/{modifier}
    controller: con4gis\ForumBundle\Controller\ForumController::personalMessageAction
    defaults: {modifier: ''}

forum_sitemap:
    path: /con4gis/forum/sitemap/{filename}
    controller: con4gis\ForumBundle\Controller\SitemapController::returnSitemap
    requirements:
        filename: ^.+\.xml$

thread_sub:
    path: /con4gis/forum/threadsub/{language}
    controller: con4gis\ForumBundle\Controller\SubscriptionController::changeThreadSubscriptionAction
    methods: [POST]

forum_sub:
    path: /con4gis/forum/forumsub/{language}
    controller: con4gis\ForumBundle\Controller\SubscriptionController::changeForumSubscriptionAction
    methods: [POST]

controllers:
    resource: '../../Controller/'
    type:     annotation
