services:
  _defaults:
    autowire: true
    autoconfigure: true

  con4gis\ForumBundle\Controller\ForumController:
    public: true
    class: con4gis\ForumBundle\Controller\ForumController

  con4gis\ForumBundle\Controller\ReactionApiController:
    public: true
    class: con4gis\ForumBundle\Controller\ReactionApiController

  con4gis\ForumBundle\Controller\SubscriptionController:
    public: true
    class: con4gis\ForumBundle\Controller\SubscriptionController

  con4gis\ForumBundle\Controller\SitemapController:
    public: true
    class: con4gis\ForumBundle\Controller\SitemapController

  con4gis\ForumBundle\Controller\ForumUploadController:
    public: true
    class: con4gis\ForumBundle\Controller\ForumUploadController

  con4gis\ForumBundle\Controller\ForumFilesController:
    public: true
    class: con4gis\ForumBundle\Controller\ForumFilesController