services:
  _defaults:
    autowire: true
    autoconfigure: true

  con4gis\ForumBundle\Controller\ForumController:
    public: true
    class: con4gis\ForumBundle\Controller\ForumController

  con4gis\ForumBundle\Controller\SubscriptionController:
    public: true
    class: con4gis\ForumBundle\Controller\SubscriptionController

  con4gis\ForumBundle\Controller\SitemapController:
    public: true
    class: con4gis\ForumBundle\Controller\SitemapController

  con4gis\ForumBundle\Controller\ProfilePageModuleController:
    tags:
      -
        name: contao.frontend_module
        category: con4gis
        renderer: forward
        template: mod_c4g_forum_profile_page